"""Guards for X2's carrier prerequisites.

The claim that matters here is a SAFETY claim - that patching `byte8[4]` yields a well-formed
instruction rather than malformed bytes - and it is the kind of claim that must not drift quietly,
because what it licenses is a dispatch. So the cases below pin it in both directions: the patched
form must decode as the same opcode at the same length on every instance, AND no vendor instance
may already set the bit (otherwise the "patch" is a no-op and proves nothing about the encoding).

The suite also asserts that the dispatch was NOT run, so that this file goes red if the evidence is
ever regenerated by something that dispatches.
"""
import json
import os
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "tools"))
sys.path.insert(0, ROOT)

EVIDENCE = os.path.join(ROOT, "tools", "tensorops-model", "x2-carrier-prerequisites.json")
MMA_INT8 = 10384


def _load():
    with open(EVIDENCE) as fh:
        return json.load(fh)


def _instances(doc):
    return [(m, i) for m in doc["modes"] if m["status"] == "ok" for i in m["instructions"]]


class TheCarrierIsOrdinaryVendorOutput(unittest.TestCase):

    def setUp(self):
        self.doc = _load()

    def test_all_four_transpose_settings_build(self):
        ok = [m for m in self.doc["modes"] if m["status"] == "ok"]
        self.assertEqual(len(ok), 4)

    def test_every_mode_emitted_the_int8_mma(self):
        for m in self.doc["modes"]:
            if m["status"] != "ok":
                continue
            self.assertGreater(m["instances"], 0, "tl=%s tr=%s" % (m["transpose_left"], m["transpose_right"]))

    def test_the_population_is_large_enough_to_carry_the_claim(self):
        self.assertGreaterEqual(len(_instances(self.doc)), 32)


class TheTransposeEncoding(unittest.TestCase):

    def setUp(self):
        self.doc = _load()

    def test_byte8_bits_2_and_3_match_the_descriptor_on_every_instance(self):
        for m, i in _instances(self.doc):
            self.assertEqual(i["transpose_left"], bool(m["transpose_left"]), i["bytes"])
            self.assertEqual(i["transpose_right"], bool(m["transpose_right"]), i["bytes"])

    def test_both_flag_values_occur(self):
        # a field that is constant across the population cannot have been shown to be the flag
        lefts = {i["transpose_left"] for _, i in _instances(self.doc)}
        rights = {i["transpose_right"] for _, i in _instances(self.doc)}
        self.assertEqual(lefts, {False, True})
        self.assertEqual(rights, {False, True})

    def test_the_three_features_are_disjoint_bits_of_one_byte(self):
        for _, i in _instances(self.doc):
            b = i["byte8"]
            self.assertEqual(bool(b >> 2 & 1), i["transpose_left"])
            self.assertEqual(bool(b >> 3 & 1), i["transpose_right"])
            self.assertEqual(bool(b >> 4 & 1), i["saturating_already"])


class ThePatchIsWellFormed(unittest.TestCase):
    """This is the claim that licenses a dispatch; it is asserted from both sides."""

    def setUp(self):
        self.doc = _load()

    def test_the_unpatched_instruction_decodes_as_the_int8_mma(self):
        for _, i in _instances(self.doc):
            self.assertIsNotNone(i["decodes_unpatched"], i["bytes"])
            self.assertEqual(i["decodes_unpatched"][0], MMA_INT8, i["bytes"])

    def test_the_patched_instruction_decodes_as_the_same_opcode_at_the_same_length(self):
        for _, i in _instances(self.doc):
            self.assertIsNotNone(i["decodes_patched"], "patched form refused: %s" % i["bytes"])
            self.assertEqual(i["decodes_patched"][0], MMA_INT8, i["bytes"])
            self.assertEqual(i["decodes_patched"][1], i["size"], i["bytes"])

    def test_no_vendor_instance_already_sets_the_saturation_bit(self):
        # if the compiler already emitted it, patching would be a no-op and prove nothing
        for _, i in _instances(self.doc):
            self.assertFalse(i["saturating_already"], i["bytes"])

    def test_the_offset_is_reported_per_instance(self):
        for _, i in _instances(self.doc):
            self.assertTrue(i["saturation_bit_at"].endswith(":4"))
            off = int(i["saturation_bit_at"].split(":")[0], 16)
            self.assertEqual(off, i["offset"] + 8)


class TheDispatchWasNotRun(unittest.TestCase):

    def test_the_evidence_records_that_nothing_was_dispatched(self):
        doc = _load()
        self.assertFalse(doc["conclusion"]["dispatch_run"],
                         "this row's dispatch is deliberately unrun; regenerating by dispatch changes what "
                         "this file is guarding")

    def test_the_remaining_work_is_named(self):
        self.assertIn("dispatch", _load()["conclusion"]["remaining"])
