// agx3remap - keep this repository's opcode and register ids when Apple's decoder renumbers them.
//
// Included by agx3dis.c and agx3dislib.c AFTER their capture globals (g_opcode, g_count, g_kind,
// g_value), which these functions read and rewrite in place. The table is tools/agx3renumber.h,
// generated by tools/g17renumber.py; that file's docstring says how it was built and what it rests on.
//
// agx3_remap_setup() runs once, after the disassembler exists, and decodes the canaries: corpus
// instructions whose old and new ids differ. All old -> the original build, nothing is translated.
// All new -> the 26A434 build, translate. Anything else -> refuse: a third numbering would otherwise
// be printed under the wrong names without a sound. AGX3_RAW=1 in the environment (or --raw on the
// CLI) skips translation, for regenerating the table itself.
#include "agx3renumber.h"

static int g_remap = -1;          // -1 not set up, 0 identity, 1 translate
static char g_remap_why[256];

typedef size_t (*Agx3DecodeFn)(void *, uint8_t *, uint64_t, uint64_t, char *, size_t);

static int agx3_hex(const char *h, uint8_t *out, int cap) {
    int n = 0;
    for (; h[0] && h[1] && n < cap; h += 2) {
        unsigned v;
        if (sscanf(h, "%2x", &v) != 1) return -1;
        out[n++] = (uint8_t)v;
    }
    return n;
}

// 0 identity, 1 translate, -1 refuse (g_remap_why says which canary and what it decoded as)
static int agx3_remap_setup(void *dc, Agx3DecodeFn disasm, int raw) {
    if (raw) { g_remap = 0; return 0; }
    int olds = 0, news = 0, n = (int)(sizeof AGX3_CANARIES / sizeof AGX3_CANARIES[0]);
    for (int i = 0; i < n; i++) {
        uint8_t buf[32]; char text[512];
        int len = agx3_hex(AGX3_CANARIES[i].hex, buf, (int)sizeof buf);
        g_opcode = 0; g_count = 0;
        size_t size = len > 0 ? disasm(dc, buf, (uint64_t)len, 0, text, sizeof text) : 0;
        int op = size == (size_t)len ? (int)g_opcode : -1;
        if (op == AGX3_CANARIES[i].old_id) olds++;
        else if (op == AGX3_CANARIES[i].new_id) news++;
        else {
            snprintf(g_remap_why, sizeof g_remap_why,
                     "canary %s decoded as %d (length %zu): neither the original id %d nor the 26A434 id %d. "
                     "This is a decoder build tools/g17renumber.py has no table for.",
                     AGX3_CANARIES[i].hex, op, size, AGX3_CANARIES[i].old_id, AGX3_CANARIES[i].new_id);
            return g_remap = -1;
        }
    }
    if (olds && news) {
        snprintf(g_remap_why, sizeof g_remap_why, "canaries split %d original / %d 26A434: no single numbering", olds, news);
        return g_remap = -1;
    }
    return g_remap = news ? 1 : 0;
}

// Rewrite the captured opcode and register operands into this repository's numbering.
static void agx3_remap_capture(void) {
    if (g_remap != 1) return;
    unsigned op = g_opcode;
    if (op == AGX3_MERGED_NEW) {
        // old 447 and 14156 merged into one form; the second immediate separates them in the corpus
        g_opcode = (g_count > 1 && g_kind[1] == 2 && g_value[1] >= AGX3_MERGED_SPLIT) ? AGX3_MERGED_HIGH
                                                                                      : AGX3_MERGED_LOW;
        if (g_count == 3 && g_kind[2] == 2 && g_value[2] == 0) g_count = 2;   // the new form's extra operand
        if (g_opcode == AGX3_MERGED_HIGH && g_count > 1) g_value[1] &= ~(int64_t)AGX3_MERGED_SPLIT;
    } else {
        g_opcode = op < AGX3_NEW_OPCODES ? (unsigned)AGX3_OP_NEW2OLD[op] : AGX3_UNMAPPED_BASE + op;
    }
    // immediates tagged in bits 29-30; a field value with no entry keeps its bits, which this slot's
    // old values never have, so it reads as a mismatch rather than as a plausible wrong value
    for (unsigned k = 0; k < g_count; k++) {
        if (g_kind[k] != 2 || !(g_value[k] & AGX3_TAG_FIELD)) continue;
        int field = (int)((g_value[k] & AGX3_TAG_FIELD) >> AGX3_TAG_SHIFT);
        for (size_t t = 0; t < sizeof AGX3_TAGS / sizeof AGX3_TAGS[0]; t++)
            if (AGX3_TAGS[t].op == (int)g_opcode && AGX3_TAGS[t].idx == (int)k && AGX3_TAGS[t].field == field) {
                g_value[k] = (g_value[k] & ~AGX3_TAG_FIELD) ^ AGX3_TAGS[t].delta;
                break;
            }
    }
    for (unsigned k = 0; k < g_count; k++) {
        if (g_kind[k] != 1) continue;                        // registers only
        int64_t r = g_value[k];
        if (r > 0 && r < AGX3_NEW_REGISTERS) g_value[k] = AGX3_REG_NEW2OLD[r];
        else if (r >= AGX3_NEW_REGISTERS) g_value[k] = AGX3_UNMAPPED_BASE + r;
    }
}
