#!/usr/bin/env python3
"""Emit the narrow pure-process allocation-layout probe from the captured A/B requests.

This is a hypothesis test, not an image builder: the two base-buffer requests
carry an AGXMetal buffer class pointer at +0x60. Probe them with that field zero,
then replay only the byte-identical tail requests if the driver accepts them.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAPTURE = ROOT / "evidence/g17-belowmetal-preflight/authored-pair-metal/passive-submit-with-requests.json"
INDICES = (0, 1, 2, 20, 22, 23, 24, 25, 26, 27, 28)


def requests():
    report = json.loads(CAPTURE.read_text())
    runs = []
    for run in report["runs"]:
        found = [m["payload"] for m in run["messages"]
                 if m.get("payload", {}).get("kind") == "submit_enter"]
        if not run["passed"] or len(found) != 1:
            raise ValueError("capture is not one passing Submit per run")
        runs.append(found[0]["allocationRequests"])
    if len(runs) != 2 or len(runs[0]) != 29 or len(runs[1]) != 29:
        raise ValueError("expected two complete 29-allocation controls")
    rows = []
    for index in INDICES:
        a, b = runs[0][index], runs[1][index]
        x, y = bytes.fromhex(a["input_hex"]), bytes.fromhex(b["input_hex"])
        differing = [i for i in range(104) if x[i] != y[i]]
        if index in (2, 20):
            if not differing or any(i not in (97, 98, 99) for i in differing):
                raise ValueError(f"base request {index} varies outside class pointer")
            x = x[:96] + bytes(8)
        elif x != y:
            raise ValueError(f"tail request {index} is not byte-stable across A/B")
        if len(x) != 104 or a["output_words"][0] != b["output_words"][0]:
            raise ValueError(f"request {index} changed shape or aperture")
        rows.append((index, x, int(a["output_words"][0]), int(a["output_words"][5])))
    return rows


def header(rows):
    lines = ["// Generated by tools/g17layoutrequests.py from the retained authored A/B capture.",
             "// Requests 2 and 20 have their AGXMetal buffer class pointer at +0x60 zeroed.",
             "// This header is for no-Submit allocation preflight only.",
             "#ifndef G17_LAYOUT_REQUESTS_H", "#define G17_LAYOUT_REQUESTS_H",
             "#include <stdint.h>",
             "struct g17_layout_request { int original_index; uint8_t input[104]; uint64_t aperture; uint64_t size; };",
             f"static const struct g17_layout_request G17_LAYOUT_REQUESTS[{len(rows)}]={{"]
    for index, request, aperture, size in rows:
        body = ",".join(str(b) for b in request)
        lines.append(f"  {{{index},{{{body}}},0x{aperture:x}ULL,0x{size:x}ULL}},")
    lines.extend(["};", "#endif", ""])
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", type=Path, default=ROOT / "spike/agxsub/g17layout_requests.h")
    args = ap.parse_args()
    rows = requests()
    text = header(rows)
    args.output.write_text(text)
    print(f"wrote {len(rows)} requests to {args.output}")
    print("sha256", hashlib.sha256(text.encode()).hexdigest())


if __name__ == "__main__":
    main()
